### ISSUE TITLE
Bug when changing window with tab

### ISSUE THREAD

**Issue by dfbarrero** [ISG-UAH/r2p2#19]
$ python r2p2.py --scenario ../conf/scenario-default.json
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "r2p2.py", line 57, in <module>
    start_simulation(args.scenario)
  File "r2p2.py", line 41, in start_simulation
    u.load_simulation(config)
  File "/home/jesus/PycharmProjects/untitled/r2p2/r2p2/utils.py", line 206, in load_simulation
    display_image(r)
  File "/home/jesus/PycharmProjects/untitled/r2p2/r2p2/utils.py", line 316, in display_image
    pressed.remove(event.key)
ValueError: list.remove(x): x not in list

**Comment by pedrosanchezr** [comment]
I have not been able to replicate, but added a check before removing the element from the list. This should resolve the issue.

The issue should be fixed in develop branch and pending to merge the PR #30

**Comment by dfbarrero** [comment]
It works smoothly, nice job.
